# Generated by Django 2.1.5 on 2019-01-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190118_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date_time']},
        ),
    ]
